name: Build UI

on:
  push:
    paths-ignore:
      - "aleph/**"
      - "contrib/**"
      - "helm/**"
      - "mappings/**"
      - "site/**"
      - "docs/**"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: echo "ALEPH_SECRET=batman\n" >> aleph.env

      - name: Build development image
        run: |
          docker build -t alephdata/aleph-ui:${GITHUB_SHA} ui
          docker tag alephdata/aleph-ui:${GITHUB_SHA} alephdata/aleph-ui:latest

      - name: Check code formatting
        run: make format-check-ui

      - name: Run linter
        run: make lint-ui

      - name: Run tests
        run: make test-ui

      - name: Build production image
        run: docker build -t alephdata/aleph-ui-production:${GITHUB_SHA} -f ui/Dockerfile.production ui

      - name: Push docker image (hash)
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: env.DOCKER_PASSWORD != null
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin 
          docker push alephdata/aleph-ui-production:${GITHUB_SHA}

      - name: Push docker image (tagged)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export ALEPH_TAG=${GITHUB_REF/refs\/tags\//}
          docker tag alephdata/aleph-ui-production:${GITHUB_SHA} alephdata/aleph-ui-production:${ALEPH_TAG};
          docker push alephdata/aleph-ui-production:${ALEPH_TAG};
          docker tag alephdata/aleph-ui-production:${GITHUB_SHA} alephdata/aleph-ui-production:latest;
          docker push alephdata/aleph-ui-production:latest;
