name: Build

on:
  push:
    paths-ignore:
      - "ui/**"

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up
        run: |
          sudo sysctl -w vm.max_map_count=262144
          sudo echo "ALEPH_SECRET=batman\n" >> aleph.env
          echo "${GITHUB_REF}"
          docker --version
          docker-compose --version

      - name: Docker pull services
        run: |
          docker-compose pull --parallel --quiet elasticsearch convert-document ingest-file
          make ALEPH_TAG=${GITHUB_SHA} services

      - name: Build docker image
        run: docker build -t alephdata/aleph:${GITHUB_SHA} .

      - name: Install development dependencies
        run: make dev

      - name: Check code formatting
        run: make format-check

      - name: Run linter
        run: make lint

      - name: Run aleph tests
        run: make ALEPH_TAG=${GITHUB_SHA} test

      - name: Push docker image (hash)
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: env.DOCKER_PASSWORD != null
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin 
          docker push alephdata/aleph:${GITHUB_SHA}

      - name: Push docker images for tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export ALEPH_TAG=${GITHUB_REF/refs\/tags\//}
          docker tag alephdata/aleph:${GITHUB_SHA} alephdata/aleph:${ALEPH_TAG};
          docker push alephdata/aleph:${ALEPH_TAG};
          docker tag alephdata/aleph:${GITHUB_SHA} alephdata/aleph:latest;
          docker push alephdata/aleph:latest;
