name: Add bugs to bugs project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/alephdata/projects/10
          github-token: ${{ secrets.ALEPH_GITHUB_TOKEN }}

name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Aleph
    steps:
    - name: Assign NEW issues and NEW pull requests to aleph
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/orgs/alephdata/projects/10'
        column_name: 'Triage'
